version: '3'

services:
  traefik:
    image: traefik:v2.10
    restart: always
    command:
      - "--api.insecure=true" # À désactiver en production
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=ton-nathan.serror@gmail.com" # Remplace par ton vrai email
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Tableau de bord Traefik (non sécurisé)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" # Lecture seule pour plus de sécurité
      - "./letsencrypt:/letsencrypt" # Stockage des certificats
    networks:
      - traefik-net

  react-app:
    build:
      context: .
      dockerfile: Dockerfile # Assure-toi que ce fichier existe
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.react-app.rule=Host(`nathan.soudry-ort.online`)" # Nom de domaine entre backticks
      - "traefik.http.routers.react-app.entrypoints=websecure"
      - "traefik.http.routers.react-app.tls.certresolver=myresolver"
      - "traefik.http.services.react-app.loadbalancer.server.port=3000" # Port interne de l'app React
    networks:
      - traefik-net

networks:
  traefik-net:
    driver: bridge